# Generated by Django 5.1.1 on 2024-09-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
