# Generated by Django 5.1 on 2024-09-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_servicestext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'About Me Text', 'verbose_name_plural': 'About Me Text'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='profileimage',
            options={'verbose_name': 'Profile Image', 'verbose_name_plural': 'Profile Image'},
        ),
        migrations.AlterModelOptions(
            name='profilevideo',
            options={'verbose_name': 'Profile Video', 'verbose_name_plural': 'Profile Video'},
        ),
        migrations.AlterModelOptions(
            name='servicestext',
            options={'verbose_name': 'Services Text', 'verbose_name_plural': 'Services Text'},
        ),
    ]
