# Generated by Django 5.1 on 2024-09-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_aboutme_options_alter_galleryimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='servicestext',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
